const fs = require('fs');

const jsonPath = "c:\\Users\\am221\\Documents\\Codex\\2026-06-26\\the-correct-existing-project-location-is\\work\\كتاب اولى ثانوي لغات.json";

if (!fs.existsSync(jsonPath)) {
  console.log("JSON not found.");
  process.exit(1);
}

const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

// The JSON generated by pdf2json has a form like { formImage: { Pages: [ { Texts: [ { R: [ { T: "encoded text" } ] } ] } ] } }
let fullText = "";

data.Pages.forEach(page => {
  page.Texts.forEach(textObj => {
    textObj.R.forEach(r => {
      // Decode URI component since pdf2json URL encodes text
      try {
        const decoded = decodeURIComponent(r.T);
        fullText += decoded + " ";
      } catch (e) {
        fullText += r.T + " ";
      }
    });
  });
  fullText += "\n\n--- PAGE BREAK ---\n\n";
});

fs.writeFileSync("decoded-pdf.txt", fullText);
console.log("Decoded text saved to decoded-pdf.txt.");
